<link rel="stylesheet" href="<?=base_url('themes/opac')?>/assets/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="<?=base_url('themes/opac')?>/assets/slick/slick.css">
<link rel="stylesheet" href="<?=base_url('themes/opac')?>/assets/slick/slick-theme.css">
<!-- icon css-->
<link rel="stylesheet" href="<?=base_url('themes/opac')?>/assets/elagent-icon/style.css">
<link rel="stylesheet" href="<?=base_url('themes/opac')?>/assets/niceselectpicker/nice-select.css">
<link rel="stylesheet" href="<?=base_url('themes/opac')?>/assets/animation/animate.css">
<link rel="stylesheet" href="<?=base_url('themes/opac')?>/assets/mcustomscrollbar/jquery.mCustomScrollbar.min.css">
<link rel="stylesheet" href="<?=base_url('themes/opac')?>/css/style-main.css">
<link rel="stylesheet" href="<?=base_url('themes/opac')?>/css/responsive.css">